apiVersion: v1
kind: Pod                                            
metadata:
  name: vault
  labels:
    app: vault                         
spec:                                                
  containers:
    - image: vault:1.13.3 
      name: vault                             
      ports:
      - name: vault-port
        containerPort: 8200
        
---

apiVersion: v1
kind: Service
metadata:
  name: vault-service
  labels:
    app: vault  
spec:
  selector:
    app: vault
  type: NodePort
  ports:
    - port: 8200
      name: vault-port
      targetPort: vault-port
      protocol: TCP